config/routes.rb
Rails.application.routes.draw do
  # get '/todo_lists' => 'todo_lists#index'
  root "todo_lists#index"
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items, dependent: :destroy
  paginates_per 3
  PRIORITY_RANGE = 1..5
  validates :title, presence: true, length: {maximum: 50}
  validates :description, length: {maximum: 200}
  validates :priority, inclusion: {in: PRIORITY_RANGE }, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todo_lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  before_action :set_todo_list
  before_action :set_todo_item, only: [:destroy, :complete]
  def create
    @todo_item = @list.todo_items.create(todo_item_params)
    redirect_to @list
  end

  def destroy
    @todo_item.destroy
    redirect_to @list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @list
  end
  private

  def set_todo_list
    @list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_todo_list, only: [:edit,:update,:show,:destroy]

  def index
    @list = TodoList.where(user_id:  current_user.id).order(priority: :desc).page params[:page]
  end

  def new
    @list = TodoList.new
  end

  def create
    @list = TodoList.new(todo_list_params)
    @list.user_id = current_user.id
    respond_to do |format|
      if @list.save
        format.html { redirect_to  @list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(todo_list_params)
      flash[:success] = "Profile  updated"
      redirect_to @list
    else
      flash[:danger] = "Profile couldn't be updated"
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @list.destroy
    redirect_to todo_lists_path
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description, :due_date, :priority)
  end

  def set_todo_list
    @list = TodoList.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="navbar navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to "Logged in as #{current_user.email}", root_path,  class: "active" %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to("Sign In", new_user_session_path, class: "active")%></li>
    <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
  <% end %>
</div><!-- /.navbar-collapse -->
<div class="container">
  <% flash.each do |message,message_type| %>
    <div class="alert alert-<%= message%>"><%= message_type %></div>
  <%end %>
  <%= yield %>
</div>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@list,@list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class=" row clear-fix">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to 'Mark as complete', complete_todo_list_todo_item_path(@list,todo_item.id), method: :patch %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.6;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to 'Delete',todo_list_todo_item_path(@list,todo_item.id), method: :delete,data: {confirm: "Are you sure?"} %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to 'Mark as complete', complete_todo_list_todo_item_path(@list,todo_item.id), method: :patch %>
    </div>
    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>
    <div class="trash">
      <%= link_to 'Delete',todo_list_todo_item_path(@list,todo_item.id), method: :delete,data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: @list, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :list_description %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, id: :datepicker %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, TodoList::PRIORITY_RANGE.to_a,{}, id: :list_priority%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> 

app/views/todo_lists/edit.html.erb
<%= render 'form', list:@list %>
<%= link_to 'Show', @list %>
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<table class="table">
<thead class="thead-dark">
<%= paginate @list %>
<tr>
  <th>Title</th>
  <th>Description</th>
  <th>Date</th>
  <th>Priority</th>
  <th colspan="3"></th>
</tr>
</thead>
  <tbody>
  <%= link_to 'New Todo List', new_todo_list_path %>
  <% @list.each do |list| %>
    <tr>
      <td> <%= list.title %> </td>
      <td> <%= list.description %> </td>
      <td> <%= list.due_date %></td>
      <td> <%= list.priority %></td>
      <td> <%= link_to 'Show',list %></td>
      <td> <%= link_to 'Delete',list, method: :delete %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/todo_lists/new.html.erb
<h1>New Todo</h1>

<%= render 'form', list:@list  %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<div class="contianer">
  <p>
    <strong>Title:</strong>
    <%= @list.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @list.description %>
  </p>

  <p>
    <strong>Date to be completed:</strong>
    <%= @list.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @list.priority %>
  </p>

  <div id="todo_items">
    <%= render @list.todo_items %>
    <div id="form">
      <%= render 'todo_items/form' %>
    </div>
  </div>

</div>
<%= link_to 'Edit', edit_todo_list_path(@list) %>
<%= link_to 'Delete',todo_lists_path  %>
<%= link_to 'Back', todo_lists_path %>